### ISSUE TITLE
Voeg een "free" field toe aan streams die gratis te kijken zijn

### ISSUE THREAD

**Issue by Sheepolution** [lekkersicko/lekker-data#12]
Zie [deze issue](https://github.com/lekkersicko/lekkersicko.github.io/issues/36) in Lekker Speuren.

1. Haal alle Youtube IDs op in [deze playlist](https://www.youtube.com/playlist?list=PLgrEkzz5vpwzjFBqXsviXdPpMKH4Ffi7W)
2. Ga door de JSON, en geef elke stream waarvan het Youtube ID in de lijst staat `"free": true`.

**Comment by braxshinoa** [comment]
done
